# This file is processed by Renovate bot so that it creates a PR on new Renovate versions.
# https://www.augmentedmind.de/2021/07/25/renovate-bot-cheat-sheet/#11-keep-up-to-date-with-renovate-bots-development
FROM renovate/renovate:42.0.0
