name: "CI"

on:
  push:

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@104620e2c495f0c905fde6f15ea2b6453ae4eaed # v3.7.0
    with:
      gradle: false
    permissions:
      contents: read
      security-events: write
      actions: read

  config:
    name: "🔍 Check Renovate"
    uses: ./.github/workflows/renovate-config-validator.yml
    permissions:
      contents: read
