name: "Validate Renovate Config"

on:
  workflow_call:

jobs:
  config:
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: "Own Config"
            config-file: .github/renovate.json5

          - name: "Shared Config"
            config-file: default.json

          - name: "Shared Config (Actual)"
            config-file: default.json5

          # Not possible yet: "Configuration Error: Invalid configuration option: all".
          #- name: "Group Presets"
          #  config-files: group.json5

    name: "${{ matrix.name }}"
    timeout-minutes: 2
    permissions:
      # actions/checkout
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Run renovate-config-validator on shared config."
        env:
          FILE: ${{ matrix.config-file }}
        shell: bash
        run: >
          npx
          --yes
          --package renovate
          --call "renovate-config-validator --strict '${FILE}'"
